version: '3.8'
services:

  test-db:
    image: postgres:16
    container_name: test-db
    ports:
      - "${DB_PORT}:5432"
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      TZ: Asia/Jakarta
    volumes:
      - test-volume:/var/lib/postgresql/data

volumes:
  test-volume:
    name: test-volume
